steps:

# Build the container image
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['source', 'repos', 'clone', 'github_fishku-id_fishku-id.github.io', '--project', 'fishku-prod']

  # Connect to GCS Bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'index.html', 'gs://landing-page-fishku-prod/index.html']

  # Connect to GCS Bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'privacy.html', 'gs://landing-page-fishku-prod/privacy.html']