steps:

# Build the container image
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['source', 'repos', 'clone', 'github_fishku-id_fishku-id.github.io', '--project', 'fishku-project-093']

  # Connect to GCS Bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'index.html', 'gs://landing-page-fishku/index.html']
